#Exercis 2.A Fundamentals of pandas

In [2]:
import pandas as pd

In [26]:
import numpy as np

# Series

Start by creating four new variables named aa, ab, ac, and ad to hold some plain
Python objects.
- Assign aa the list 1,2,3,4.
- Assign ab the tuple 5,6,7,8.
- Assign ac the set 9,10,11,12.
- Assign ad a dictionary with the following key-value pairs:
'first': 13, 'second': 14, 'third': 15, 'fourth': 16

In [3]:
aa = [1,2,3,4]
ab = (5,6,7,8)
ac = {9,10,11,12}
ad = {'first':13,'second':14,'third':15,'fourth':16}

Create four new variables named ser1, ser2, ser3, and ser4. Assign to each a
Series created from one of the previous four variables.
- ser1 should use aa
- ser2 should use ab
- ser3 should use ac
- ser4 should use ad

In [4]:
ser1 = pd.Series(aa)

In [5]:
ser2 = pd.Series(ab)

In [6]:
ser3 = pd.Series(list(ac))

In [7]:

ser4 = pd.Series(ad)

In [8]:
print(ser1)

0    1
1    2
2    3
3    4
dtype: int64

In [9]:
print(ser2)

0    5
1    6
2    7
3    8
dtype: int64

In [10]:
print(ser3)

0     9
1    10
2    11
3    12
dtype: int64

In [11]:
print(ser4)

first     13
second    14
third     15
fourth    16
dtype: int64

In a new cell, create a variable named ser5 and assign it the literal values 17, 18,
19, 20. When you run the cell, what happens? Add a comment to the cell with the
specific TypeError message that arises.

In [12]:
ser5 = {17,18,19,20}

In [13]:
print(ser5[3])
# typeErro: set object is not subscriptable

TypeError: 'set' object is not subscriptable

## DataFrames from Series

Create new variable df1 and give it the value of a DataFrame using ser1. Then on
the next line, call df1 by simply typing in the variable name (no print function).
When you run the cell, a simple formatted DataFrame should be returned.

In [ ]:
df1 = pd.DataFrame(ser1)

In [ ]:
df1

Add two new columns to df1 via the insert() method using ser2 and ser3 for each
column. Call df1 to review the updated DataFrame.

In [ ]:
df1.insert(1,"ser2",ser2)
df1.insert(2,"ser3",ser3)
df1

Add a third new column to df1 using ser4. What happens this time when you call
df1? Add a comment explaining the difference between ser4 compared to the
other Series data used, and how this affected the outcome

In [ ]:
df1.insert(3,"ser4",ser4)

In [ ]:
df1

In [ ]:
# seems like the values arent registering ,mabye because they have keys and values

Add a new row 4 using the loc attribute with the values 5, 9, 12, 0. Call df1 to review
the updated DataFrame

In [ ]:
df1.loc[4] = [5,9,12,0]

In [ ]:
df1

## Reading Data into a DataFrame

Create a new variable df2. Use the read_csv function to read the contents of
sakila_example.csv into df2. (Note that you will need to save the CSV file to the
same folder where Jupyter Notebook is running for this exercise.) Call df2 to review
the resul

In [17]:
df2 = pd.read_csv("sakila_example.csv")

Display the top 5 records from df2.

In [18]:
df2.head()

,title,description,category,language,actor_name
0,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,PENELOPE GUINESS
1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,CHRISTIAN GABLE
2,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,LUCILLE TRACY
3,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,SANDRA PECK
4,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,JOHNNY CAGE

Display the last 10 records from df2

In [19]:
df2.tail()

,title,description,category,language,actor_name
257,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,GARY PENN
258,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,CHRISTOPHER WEST
259,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,DUSTIN TAUTOU
260,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,ANGELA HUDSON
261,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,JAMES PITT

Show summary information about df2 using the info method.

df2.info()

 by reviewing the data frame with infor we can see we have 5 columbs ,total of 262 entries ,memory usage of 10.4 kb

Create a new variable df3. Use the read_csv function to read the contents of
northwind_example.csv into df3. (Note again that you will need to save the CSV file
to the same folder where Jupyter Notebook is running for this exercise.) Call df3 to
review the result.

In [21]:
df3  = pd.read_csv("northwind_example.csv")

 Show column statistics on df3 using the describe method

In [23]:
df3.describe()

            OrderID   UnitPrice    Quantity
count      8.000000    8.000000    8.000000
mean    7825.475833  102.188229   90.674963
std     4660.745423  174.570984  169.481509
min       54.442663    2.000000    1.000000
25%     7811.000000   14.450000   16.052276
50%    10317.500000   25.352918   22.165000
75%    10353.273000   73.550000   54.000000
max    10436.000000  500.000000  500.000000

Add a markdown cell. Looking at the describe results, what are the useful insights
you can take away? How are the summarizations here different than for the
previous example, and why?

it gives me all functions that may be important in future for ex max,mix,mean etc. Goes more into detail for data frame

## Coding a DataFrame

Create a new variable named test_data and assign it a dictionary with the
following key-value pairs:
'ID': [1, 2, 3, 4, 5, 6, 7, 8],
'Name': ['Alicia', 'Bob', 'Charlie', 'Dominic', 'Eve', 'Frank', 'Grace', 'Heidi'],
'Age': [25, np.nan, 22, 19, 31, 35, np.nan, 18],
'City': ['NY', 'LA', 'Chicago', 'Houston', 'Phoenix', 'Boston', 'Austin', 'San Diego'],
'Score': [85, 92, -1, 65, 78, np.nan, 55, 90]

In [27]:
test_data = {'ID': [1, 2, 3, 4, 5, 6, 7, 8],
'Name': ['Alicia', 'Bob', 'Charlie', 'Dominic', 'Eve', 'Frank', 'Grace', 'Heidi'],
'Age': [25, np.nan, 22, 19, 31, 35, np.nan, 18],
'City': ['NY', 'LA', 'Chicago', 'Houston', 'Phoenix', 'Boston', 'Austin', 'San Diego'],
'Score': [85, 92, -1, 65, 78, np.nan, 55, 90]}

In [30]:
df4 = pd.DataFrame(test_data)

In [31]:
df4

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [33]:
df4.to_csv("test_data.csv",index=False)